# Generated by Django 5.0.6 on 2024-07-07 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 7, 7, 18, 28, 15, 727592), upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
