# Generated by Django 5.0.6 on 2024-07-08 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_user'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='account.account'),
        ),
    ]
