# Generated by Django 5.0.6 on 2024-07-06 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_description_alter_category_name_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsection',
            name='blog',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=datetime.datetime(2024, 7, 6, 14, 35, 59, 419218)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogSection',
        ),
    ]
