# Generated by Django 5.0.6 on 2024-07-06 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='heading',
            field=models.CharField(default=datetime.datetime(2024, 7, 6, 19, 33, 30, 606791), max_length=100),
            preserve_default=False,
        ),
    ]
